### ISSUE TITLE
Red Guard (Gloomhaven Jaws of the Lion)

### ISSUE THREAD

**Issue by redheadpopeye** [acs027/Gloomhaven-Attacker#23]
For Red Guard (Gloomhaven Jaws of the Lion), the cards do not show up correctly when flipped over.

Specifically, the following cards do not show up correctly in the deck. This is not a compete list.
-Add one +1 Shield card
-Add one +1 Fire element and Sun element card
-Replace a +1 card with a +2 Fire element card
-Replace a +1 card with a +2 Sun element card

**Comment by acs027** [comment]
Thank you for your feedback. We fixed it on here. It will be at Appstore soon aswell.
